# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e39cf934f1360eac16f03f1c010da976"
name = "bundle-app"
handle = "bundle-app-155"
application_url = "https://parks-advisors-sustainable-mart.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststoreplatform.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://parks-advisors-sustainable-mart.trycloudflare.com/auth/callback",
  "https://parks-advisors-sustainable-mart.trycloudflare.com/auth/shopify/callback",
  "https://parks-advisors-sustainable-mart.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
